### ISSUE TITLE
Error loading pts_in_hull.npy

### ISSUE THREAD

**Issue by smacm** [mauckc/colorize-video#3]
Ran into this error trying to run the V2 script:

_python3 colorizeVideoV2.py -i BW.mp4 -o Col.mp4

Starting timing... 

[INFO] warming up camera...
Traceback (most recent call last):
  File "colorizeVideoV2.py", line 78, in <module>
    pts_in_hull = np.load('./pts_in_hull.npy')
  File "/usr/local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 444, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False_

(apparently numpy recently changed the default value of allow_pickle?

I added allow_pickle=True to the call
   _pts_in_hull = np.load('./pts_in_hull.npy', allow_pickle=True)_

But then I just got a different error:

_Starting timing..._ 

_[INFO] warming up camera...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "colorizeVideoV2.py", line 78, in <module>
    pts_in_hull = np.load('./pts_in_hull.npy', allow_pickle=True)
  File "/usr/local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 449, in load
    raise IOError(
OSError: Failed to interpret file './pts_in_hull.npy' as a pickle_

**Comment by smacm** [comment]
.... I just looked.  Apparently pts_in_hull.npy is an empty file.  Did I miss a step?

**Comment by smacm** [comment]
... apparently Rich Zhang has removed pts_in_hull.npy from his github account.

**Comment by smacm** [comment]
In fact, a couple of the models are gone:

--2020-09-13 23:21:25--  https://github.com/richzhang/colorization/blob/master/colorization/resources/pts_in_hull.npy?raw=true
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-13 23:21:25 ERROR 404: Not Found.

--2020-09-13 23:21:25--  https://raw.githubusercontent.com/richzhang/colorization/master/colorization/models/colorization_deploy_v2.prototxt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.192.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-13 23:21:26 ERROR 404: Not Found.

--2020-09-13 23:21:26--  http://people.eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v2/colorization_release_v2.caffemodel
Resolving people.eecs.berkeley.edu (people.eecs.berkeley.edu)... 128.32.189.73
Connecting to people.eecs.berkeley.edu (people.eecs.berkeley.edu)|128.32.189.73|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 128946764 (123M)
Saving to: ‘./models/colorization_release_v2.caffemodel’

./models/colorization_release_v2.caff 100%[===========================================================================>] 122.97M  2.46MB/s   in 59s    

2020-09-13 23:22:25 (2.10 MB/s) - ‘./models/colorization_release_v2.caffemodel’ saved [128946764/128946764]

--2020-09-13 23:22:25--  http://people.eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v2/colorization_release_v2_norebal.caffemodel
Resolving people.eecs.berkeley.edu (people.eecs.berkeley.edu)... 128.32.189.73
Connecting to people.eecs.berkeley.edu (people.eecs.berkeley.edu)|128.32.189.73|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 128946454 (123M)
Saving to: ‘./models/colorization_release_v2_norebal.caffemodel’

./models/colorization_release_v2_nore 100%[===========================================================================>] 122.97M  2.71MB/s   in 49s    

2020-09-13 23:23:14 (2.49 MB/s) - ‘./models/colorization_release_v2_norebal.caffemodel’ saved [128946454/128946454]

**Comment by sblackstone** [comment]
Try here for pts_in_hull...

https://github.com/richzhang/colorization/blob/8aa25ac7b6215bf6789e682b6fa3433164d4a3a4/resources/pts_in_hull.npy

**Comment by sblackstone** [comment]
And .prototxt - looks like someone tried to use the same files in another project as this works...

https://raw.githubusercontent.com/alexellis/faas-colorization/master/function/models/colorization_deploy_v2.prototxt

**Comment by smacm** [comment]
Thanks.  As soon as I get some time, I'll circle back to this.

Steve

**Comment by mauckc** [comment]
Thanks @sblackstone I added your URLs to the getModels.sh file.

**Comment by sblackstone** [comment]
@mauckc I'd just copy the hull file in, its tiny, like 6k.

As for the other, you might want to put it somewhere stable as if alexellis/faas-colorization ever gets deleted, this would stop working.

**Comment by mauckc** [comment]
@sblackstone done
